### ISSUE TITLE
請求關於Z1的幫助

### ISSUE THREAD

**Issue by maodun96** [jomud9/homeassistant_howto#4]
你好，我是來自大陸的網友。因為搜尋到你Z1相關的轉換器才找到這邊。
通過使用你提供的轉換器，成功驅動了雙鍵版本。
因為我家使用了單鍵、雙鍵和三鍵三種類型的Z1，想請問你是否有編寫Z1單鍵的轉換器。

期盼回覆，感謝。

**Comment by jomud9** [comment]
首先，多謝聯絡。

最近有點忙，沒有更新。星期日有空我給你試試單鍵的版本 。

等我喔～

**Comment by maodun96** [comment]
那我就敬候佳音了。感謝你的幫助！

**Comment by jomud9** [comment]
譏謝你的等候, 你試試看?

https://github.com/Koenkk/zigbee2mqtt/issues/19842

**Comment by maodun96** [comment]
> 譏謝你的等候, 你試試看?
> 
> [Koenkk/zigbee2mqtt#19842](https://github.com/Koenkk/zigbee2mqtt/issues/19842)

![image](https://github.com/jomud9/homeassistant_howto/assets/43996175/74eaa8bc-7051-4ca9-8e62-08d84f0c36a6)
感謝你的幫助，我已經通過zigbee2mqtt成功驅動單鍵Z1。基礎功能都可以使用。Lock relay功能無效；跟雙鍵相比，似乎缺少了狀態燈的設置。

**Comment by jomud9** [comment]
我試試再修改一下, 到時想找你測試

**Comment by maodun96** [comment]
> 我試試再修改一下, 到時想找你測試

好的，到時候你聯絡我，我配合你。
